---
- name: manage a user
  hosts: all
  tasks:
    - name: Add the user 'luigi' with a specific uid and a primary group of 'admin'
      user:
        name: luigi
        comment: luigi colagiorgio
        uid: 1040
        group: users


    - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      user:
        name: luigi
        shell: /bin/bash
        groups: users,wheel
        append: yes


    - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
      user:
        name: luigi
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/luigi_id_rsa



    - name: Remove the user 'luigi'
      user:
        name: toto
        state: absent
        remove: yes

    